[package]
name = "octopus"
version = "0.1.0"
authors = ["snlan"]

[dependencies]
mysql = "15.0.0"
redis = "0.9.1"
sha1 = "0.6.0"
serde_json = "1.0.37"
failure = "0.1.5"
log = "0.4.6"
env_logger = "0.6.0"
zookeeper = "0.5.5"
threadpool = "1.7.1"